// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM-SQ5htfgU_zQfCo1juZKAT3ftF-VVl4',
    appId: '1:947209665069:web:969917df4b58665b1796a4',
    messagingSenderId: '947209665069',
    projectId: 'pcmart-a5026',
    authDomain: 'pcmart-a5026.firebaseapp.com',
    storageBucket: 'pcmart-a5026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UJzUCJyll-w_dbT-rTjqawg-2Fe457U',
    appId: '1:947209665069:android:e3d75e980897a71d1796a4',
    messagingSenderId: '947209665069',
    projectId: 'pcmart-a5026',
    storageBucket: 'pcmart-a5026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGEWrvVLmre1oQwHMP5FY3E7y4Tm796E',
    appId: '1:947209665069:ios:83b2c8fce6e676271796a4',
    messagingSenderId: '947209665069',
    projectId: 'pcmart-a5026',
    storageBucket: 'pcmart-a5026.appspot.com',
    iosClientId: '947209665069-cbk5jg4us7ijr9c5so4up09m3v488c1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdGEWrvVLmre1oQwHMP5FY3E7y4Tm796E',
    appId: '1:947209665069:ios:83b2c8fce6e676271796a4',
    messagingSenderId: '947209665069',
    projectId: 'pcmart-a5026',
    storageBucket: 'pcmart-a5026.appspot.com',
    iosClientId: '947209665069-cbk5jg4us7ijr9c5so4up09m3v488c1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
